- name: adding mongodb repository for amazon linux 2
  ansible.builtin.yum_repository:
    name: mongodb-org-4.2
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
    description: MongoDB Repository
    gpgcheck: false
    enabled: true
    state: present
