- ansible.builtin.debug:
    msg: "{{ service }}"

- name: starting and enabling mysql
  ansible.builtin.service:
    become: true
    become_user: root
    name: "{{ service }}"
    state: started
    enabled: true
    daemon_reload: true
