---
- name: configuring cart
  hosts: localhost
  become: true
  tasks:
    - include_role:
        name: install_nodejs

    - include_role:
        name: add_roboshop_user

    - name: creating /app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: downloading source files
      ansible.builtin.unarchive:
        src: https://roboshop-builds.s3.amazonaws.com/cart.zip
        dest: /app
        remote_src: true

    - name: installing dependencies
      ansible.builtin.command:
        cmd: npm install
        chdir: /app

    - name: configuring cart service
      ansible.builtin.copy:
        content: |
          [Unit]
          Description = Cart Service
          [Service]
          User=roboshop
          Environment=REDIS_HOST=redis.devopsplay.online
          Environment=CATALOGUE_HOST=catalouge.deveopsplay.online
          Environment=CATALOGUE_PORT=8080
          ExecStart=/bin/node /app/server.js
          SyslogIdentifier=cart

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/cart.service

    - name: starting cart service
      ansible.builtin.systemd:
        daemon-reload: true
        name: cart
        state: started
        enabled: true
