---
- name: Catalouge configuration
  hosts: localhost
  become: yes
  tasks:
    - name: installing nodejs
      ansible.builtin.yum:
        name: "{{item}}"
        state: present
      loop:
        - https://rpm.nodesource.com/pub_16.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm
        - nodejs

    - name: adding roboshop user
      ansible.builtin.user:
        name: roboshop
        state: present

    - name: creating /app directory
      ansible.builtin.file:
        path: ./app
        state: directory

    - name: downloading catalouge code
      ansible.builtin.unarchive:
        scr: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /app
        remote_scr: yes

    - name: downloading dependencies
      ansible.builtin.command:
        cmd: npm install
        args:
          chdir: /app

    - name: creating catalouge service
      ansible.builtin.copy:
        src: ../config/catalouge.service
        dest: /etc/systemd/system/catalogue.service
        remote_src: true

    - name: demaon reload and stating, enabling catalouge service
      ansible.builtin.systemd:
        daemon_reload: true
        name: catalogue
        state: started
        enabled: true

    - name: adding mongodb repository for amazon linux 2
      ansible.builtin.yum_repository:
        name: mongodb-org-4.2
        baseurl: https://repo.mongodb.org/yum/amazon/2/mongodb-org/4.2/x86_64/
        description: MongoDB Repository
        gpgkey: https://www.mongodb.org/static/pgp/server-4.2.asc
        enabled: true
        state: present

    - name: installing mongodb
      ansible.builtin.package:
        name: mongodb-org-shell
        state: present

    - name: loading schema
      ansible.builtin.command:
        cmd: "mongo --host MONGODB-SERVER-IPADDRESS </app/schema/catalogue.js"
