---
- name: Catalouge configuration
  hosts: catalouge
  become: yes
  tasks:
    - include_role:
        name: install_nodejs

    - include_role:
        name: add_roboshop_user

    - name: creating /app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: downloading catalouge code
      ansible.builtin.unarchive:
        src: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /app
        remote_src: yes

    - name: downloading dependencies
      ansible.builtin.command:
        cmd: npm install
        chdir: /app

    - name: creating catalouge service
      ansible.builtin.copy:
        src: ../config/catalouge.service
        dest: /etc/systemd/system/catalogue.service
        remote_src: true

    - name: demaon reload and stating, enabling catalouge service
      include_role:
        name: service_enable_start
      vars:
        - service: catalouge

    - include_role:
        name: mongo_repo

    - name: installing mongodb
      ansible.builtin.package:
        name: mongodb-org-shell
        state: present

    - name: loading schema
      ansible.builtin.command:
        cmd: "mongo --host mongo.devopsground.online </app/schema/catalogue.js"
