---
- name: Configuring mongodb server
  hosts: localhost
  become: true
  tasks:
    - name: printing facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: adding mongodb repository for amazon linux 2
      ansible.builtin.yum_repository:
        name: mongodb-org-4.2
        baseurl: https://repo.mongodb.org/yum/amazon/2/mongodb-org/4.2/x86_64/
        description: MongoDB Repository
        gpgkey: https://www.mongodb.org/static/pgp/server-4.2.asc
        enabled: true
        state: present

    - name: installing mongodb
      ansible.builtin.package:
        name: mongodb-org
        state: present

    - name: making mongodb open to internet
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: "127.0.0.1"
        replace: "0.0.0.0"

    - name: starting mongodb service
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes
