---
- name: Configuring mongodb server
  hosts: mongo
  become: true
  tasks:
    - include_role:
        name: mongo_repo

    - name: installing mongodb
      ansible.builtin.package:
        name: mongodb-org
        state: present

    - name: making mongodb open to internet
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: "127.0.0.1"
        replace: "0.0.0.0"

    - name: starting mongodb service
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes
