---
- name: redis configuration
  hosts: localhost
  become: true
  tasks:
    - name: checking and installing redis
      block:
        - name: installing redis
          ansible.builtin.package:
            name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
            state: present

        - name: enabling redis repo
          ansible.builtin.command:
            cmd: yum module enable redis:remi-6.2 -y

        - name: enabling and installing redis
          ansible.builtin.yum:
            name: redis
            state: present

        - name: opening config to public
          ansible.builtin.replace:
            path: /etc/redis/redis.conf
            regexp: "127.0.0.1"
            replace: "0.0.0.0"
      when: ansible_facts['distribution'] == 'CentOS'
      notify: starting and enabling redis

  handlers:
    - name: starting and enabling redis
      ansible.builtin.systemd:
        name: redis
        state: started
        enabled: true
        daemon_reload: true
