---
- name: redis configuration
  hosts: redis
  become: true
  tasks:
    - name: checking and installing redis
      block:
        - name: installing redis
          ansible.builtin.package:
            name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
            state: present

        - name: enabling and installing redis
          ansible.builtin.yum:
            name: redis
            enablerepo: redis:remi-6.2
            state: present

        - name: opening config to public
          ansible.builtin.replace:
            path: /etc/redis/redis.conf
            regexp: "127.0.0.1"
            replace: "0.0.0.0"
      when: ansible_facts['distribution'] == 'CentOS'
      notify: starting and enabling mysql
