---
- name: redis configuration
  hosts: redis
  become: true
  tasks:
    - name: installing redis
      ansible.builtin.package:
        name: redis
        state: present

    - name: opening config to public
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: "127.0.0.1"
        replace: "0.0.0.0"

    - name: starting and enabling redis service
      ansible.builtin.service:
        name: redis
        state: started
        enabled: yes
