---
- name: configuring user host
  hosts: user
  become: true
  tasks:
    - name: installing nodejs
      include_role:
        name: install_nodejs

    - name: adding roboshop user
      include_role:
        name: add_roboshop_user

    - name: Creating /app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: downloading user code
      ansible.builtin.unarchive:
        src: https://roboshop-builds.s3.amazonaws.com/user.zip
        dest: /app
        remote_src: true

    - name: downloading and installing dependencies
      ansible.builtin.command:
        cmd: npm install
        chdir: /app

    - name: Configuring user service
      ansible.builtin.copy:
        content: |
          [Unit]
          Description = User Service
          [Service]
          User=roboshop
          Environment=MONGO=true
          Environment=REDIS_HOST=<REDIS-SERVER-IP>
          Environment=MONGO_URL="mongodb://mongo.devopsground.online:27017/users"
          ExecStart=/bin/node /app/server.js
          SyslogIdentifier=user

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/user.service
        remote_src: true

    - name: reloading and enabling user service
      include_role:
        name: service_enable_start
      vars:
        - service: user

    - name: adding mongodb repository for amazon linux 2
      include_role:
        name: mongo_repo

    - name: installing mongodb
      ansible.builtin.package:
        name: mongodb-org-shell
        state: present

    - name: loading schema
      ansible.builtin.command:
        cmd: mongo --host mongo.devopsground.online </app/schema/user.js
