---
- name: Configuring Web Server
  hosts: web
  become: yes
  tasks:
    - name: checking package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: checking service status
      ansible.builtin.service_facts:

    - name: Installing nginx
      ansible.builtin.package:
        name: nginx
        state: present
      when: ansible_facts.packages.nginx

    - name: Delete default nginx page and create any empty html directory
      block:
        - name: Deletting html folder
          ansible.builtin.file:
            path: /usr/share/nginx/html
            state: absent
        - name: Creating empty html folder
          ansible.builtin.file:
            path: /usr/share/nginx/html
            state: directory

    - name: Download web contents
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/web.zip
        dest: /tmp

    - name: Unzipping web contents
      ansible.builtin.unarchive:
        src: /tmp/web.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Configuring roboshop
      ansible.builtin.copy:
        src: ./config/roboshop.conf
        dest: /etc/nginx/default.d/roboshop.conf

    - name: Starting and enabling nginx
      include_role:
        name: service_enable_start
      vars:
        - service: nginx
