- name: setting up nodejs repo
  ansible.builtin.command:
    cmd: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: installing nodejs
  ansible.builtin.yum:
    name: nodejs
    state: present
