- name: installing nodejs
  ansible.builtin.yum:
    name: "{{item}}"
    state: present
  loop:
    - https://rpm.nodesource.com/pub_16.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm
    - nodejs
